packages:
  - 'client'
  - 'server'
  - 'packages/*'
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  '@sentry/node-cpu-profiler': set this to true or false
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - axios@1.19.0
